import React, { useState } from 'react';
import { Plus, Minus, Send, Receipt } from 'lucide-react';
import { POS_CATALOG } from '../data/mockData';
import { buildWhatsAppLink } from '../utils/whatsapp';

export const PosDemo = ({ onTriggerToast }) => {
  const [cart, setCart] = useState([
    { id: 'pos-1', name: 'Paneer Tikka Roll', price: 180, qty: 1 },
    { id: 'pos-3', name: 'Cold Brew Coffee (300ml)', price: 140, qty: 1 }
  ]);
  const [customerPhone, setCustomerPhone] = useState('9511896416');

  const addToCart = (item) => {
    setCart((prev) => {
      const existing = prev.find((p) => p.id === item.id);
      if (existing) {
        return prev.map((p) =>
          p.id === item.id ? { ...p, qty: p.qty + 1 } : p
        );
      }
      return [...prev, { ...item, qty: 1 }];
    });
  };

  const updateQty = (id, delta) => {
    setCart((prev) =>
      prev
        .map((item) => {
          if (item.id === id) {
            const newQty = item.qty + delta;
            return newQty > 0 ? { ...item, qty: newQty } : null;
          }
          return item;
        })
        .filter(Boolean)
    );
  };

  const subtotal = cart.reduce((acc, item) => acc + item.price * item.qty, 0);
  const cgst = Math.round(subtotal * 0.025);
  const sgst = Math.round(subtotal * 0.025);
  const total = subtotal + cgst + sgst;

  const handleCheckout = () => {
    if (!customerPhone.trim()) {
      if (onTriggerToast) {
        onTriggerToast('error', 'Mobile Required', 'Enter customer phone number.');
      }
      return;
    }

    if (cart.length === 0) {
      if (onTriggerToast) {
        onTriggerToast('error', 'Cart Empty', 'Add items from catalog.');
      }
      return;
    }

    const itemLines = cart.map(
      (item) => `• ${item.name} x ${item.qty} = ₹${item.price * item.qty}`
    );

    const invoiceText =
      `*FREESTYLE SYSTEMS — TAX INVOICE*\n` +
      `*Invoice:* FS-INV-${Math.floor(1000 + Math.random() * 9000)}\n` +
      `--------------------\n` +
      itemLines.join('\n') +
      `\n--------------------\n` +
      `*Subtotal:* ₹${subtotal}\n` +
      `*GST (5%):* ₹${cgst + sgst}\n` +
      `*TOTAL:* ₹${total}\n\n` +
      `_Paperless digital invoice generated by FreeStyle Systems._`;

    const waUrl = buildWhatsAppLink(customerPhone, invoiceText);
    window.open(waUrl, '_blank', 'noopener,noreferrer');

    if (onTriggerToast) {
      onTriggerToast('success', 'Invoice Sent', `WhatsApp receipt generated for ₹${total}.`);
    }
  };

  return (
    <div className="space-y-4">
      
      {/* 6-Item Product Grid */}
      <div className="grid grid-cols-2 sm:grid-cols-3 gap-2">
        {POS_CATALOG.map((item) => {
          const inCart = cart.find((c) => c.id === item.id);
          return (
            <button
              key={item.id}
              onClick={() => addToCart(item)}
              className="p-2.5 bg-white hover:bg-blue-50/40 border border-slate-200 hover:border-blue-400 rounded-xl text-left transition flex flex-col justify-between relative min-h-[64px] group"
            >
              <div>
                <div className="text-xs font-bold text-slate-900 group-hover:text-blue-600 truncate">
                  {item.name}
                </div>
                <div className="text-[10px] text-slate-400">{item.category}</div>
              </div>

              <div className="flex items-center justify-between pt-1 mt-1 border-t border-slate-100">
                <span className="text-xs font-mono font-bold text-slate-800">
                  ₹{item.price}
                </span>
                <span className={`px-2 py-0.5 rounded-md font-bold text-[11px] flex items-center gap-1 transition ${
                  inCart ? 'bg-blue-600 text-white shadow-2xs' : 'bg-blue-50 text-blue-600 group-hover:bg-blue-600 group-hover:text-white'
                }`}>
                  {inCart ? `✓ (${inCart.qty})` : '+ Add'}
                </span>
              </div>
            </button>
          );
        })}
      </div>

      {/* Cart & Checkout Panel */}
      <div className="p-3 sm:p-4 bg-slate-50 rounded-2xl border border-slate-200 space-y-3">
        <div className="flex items-center justify-between pb-2 border-b border-slate-200 text-xs">
          <div className="flex items-center gap-1.5 font-bold text-slate-900">
            <Receipt className="w-3.5 h-3.5 text-blue-600" />
            <span>Order Summary</span>
          </div>
          {cart.length > 0 && (
            <button
              onClick={() => setCart([])}
              className="text-slate-400 hover:text-red-600 text-[11px]"
            >
              Clear
            </button>
          )}
        </div>

        {/* Itemized Cart List */}
        {cart.length === 0 ? (
          <div className="py-3 text-center text-xs text-slate-400">
            Tap items above to bill.
          </div>
        ) : (
          <div className="space-y-1.5">
            {cart.map((item) => (
              <div
                key={item.id}
                className="flex items-center justify-between p-2 bg-white rounded-lg border border-slate-200 text-xs"
              >
                <div className="truncate flex-1 pr-2">
                  <div className="font-bold text-slate-900 truncate">{item.name}</div>
                  <div className="text-slate-400 text-[10px]">₹{item.price}</div>
                </div>

                <div className="flex items-center gap-2">
                  <div className="flex items-center border border-slate-200 rounded bg-slate-50">
                    <button
                      onClick={() => updateQty(item.id, -1)}
                      className="px-1.5 py-0.5 text-slate-600 hover:text-slate-900"
                    >
                      <Minus className="w-3 h-3" />
                    </button>
                    <span className="px-1 font-mono font-bold text-slate-900 text-xs">
                      {item.qty}
                    </span>
                    <button
                      onClick={() => updateQty(item.id, 1)}
                      className="px-1.5 py-0.5 text-slate-600 hover:text-slate-900"
                    >
                      <Plus className="w-3 h-3" />
                    </button>
                  </div>

                  <span className="font-mono font-bold text-slate-900 w-12 text-right">
                    ₹{item.price * item.qty}
                  </span>
                </div>
              </div>
            ))}
          </div>
        )}

        {/* Price Breakdown */}
        {cart.length > 0 && (
          <div className="pt-2 border-t border-slate-200 flex items-center justify-between text-xs">
            <span className="text-slate-500">GST (5%) Included: ₹{cgst + sgst}</span>
            <div className="flex items-center gap-1.5">
              <span className="text-slate-500">Total:</span>
              <span className="font-mono font-black text-emerald-600 text-sm">₹{total}</span>
            </div>
          </div>
        )}

        {/* Customer Mobile Field & Action */}
        <div className="pt-1 flex flex-col sm:flex-row gap-2">
          <div className="relative flex-1">
            <span className="absolute left-2.5 top-1/2 -translate-y-1/2 text-xs font-mono font-bold text-slate-400">
              +91
            </span>
            <input
              type="tel"
              value={customerPhone}
              onChange={(e) => setCustomerPhone(e.target.value)}
              placeholder="10-digit mobile"
              className="w-full pl-10 pr-3 py-2 bg-white border border-slate-300 rounded-xl text-xs font-mono focus:outline-none focus:ring-2 focus:ring-blue-500 min-h-[40px]"
            />
          </div>

          <button
            onClick={handleCheckout}
            disabled={cart.length === 0}
            className="inline-flex items-center justify-center gap-1.5 px-4 py-2 bg-blue-600 hover:bg-blue-700 text-white font-bold rounded-xl text-xs shadow-sm transition disabled:opacity-50 min-h-[40px]"
          >
            <Send className="w-3.5 h-3.5" />
            <span>Complete & Send Invoice</span>
          </button>
        </div>

      </div>

    </div>
  );
};
